name: Build on Windows (choco-only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain and cmake via Chocolatey
        shell: powershell
        run: |
          choco install -y mingw msys2 make cmake
          Start-Sleep -Seconds 5

      - name: Add mingw to PATH
        run: echo "C:\tools\mingw64\bin" >> $GITHUB_PATH

      - name: Run Windows build batch
        shell: cmd
        run: |
          @echo off
          cls
          cmake -D CMAKE_C_COMPILER=i686-w64-mingw32-gcc -D CMAKE_CXX_COMPILER=i686-w64-mingw32-g++ -G "MinGW Makefiles" -Wno-dev zydis -B zydis
          cmake -D CMAKE_C_COMPILER=i686-w64-mingw32-gcc -D CMAKE_CXX_COMPILER=i686-w64-mingw32-g++ -G "MinGW Makefiles" -Wno-dev zydis\dependencies\zycore -B zydis\dependencies\zycore
          cmake -D CMAKE_C_COMPILER=i686-w64-mingw32-gcc -D CMAKE_CXX_COMPILER=i686-w64-mingw32-g++ -G "MinGW Makefiles" -Wno-dev -B CMake
          mingw32-make -C CMake -s

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: CMake/**/*
