name: Build on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2 and install packages
        uses: msys2/setup-msys2@v3
        with:
          update: true
          install: >
            mingw-w64-i686-gcc
            mingw-w64-i686-g++
            mingw-w64-i686-make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-g++
            mingw-w64-x86_64-make
            cmake

      - name: Add MSYS2 mingw32 to PATH
        run: |
          echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH

      - name: Run Windows build batch
        shell: cmd
        run: |
          @echo off
          cls
          cmake -D CMAKE_C_COMPILER=i686-w64-mingw32-gcc -D CMAKE_CXX_COMPILER=i686-w64-mingw32-g++ -G "MinGW Makefiles" -Wno-dev zydis -B zydis
          cmake -D CMAKE_C_COMPILER=i686-w64-mingw32-gcc -D CMAKE_CXX_COMPILER=i686-w64-mingw32-g++ -G "MinGW Makefiles" -Wno-dev zydis\dependencies\zycore -B zydis\dependencies\zycore
          cmake -D CMAKE_C_COMPILER=i686-w64-mingw32-gcc -D CMAKE_CXX_COMPILER=i686-w64-mingw32-g++ -G "MinGW Makefiles" -Wno-dev -B CMake
          mingw32-make -C CMake -s

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: CMake/**/*
